const choice = (label, answer, group) => `<button class="choice-button" type="button" data-answer="${answer}" data-group="${group}">${label}</button>`;
const reveal = (label, answer) => `<button class="reveal-button" type="button" data-reveal>Reveal ${label}</button><div class="answer-panel">${answer}</div>`;
const sort = (items, id) => `<div class="sort-bank" data-sort="${id}">${items.map(([word, correct]) => `<button class="sort-button" type="button" data-correct="${correct}">${word}</button>`).join("")}</div><div class="button-row"><button class="primary-button" type="button" data-check="${id}">Check</button><button class="secondary-button" type="button" data-reset="${id}">Reset</button></div><p class="feedback" data-feedback="${id}">Tap each item: 1 = first category, 2 = second category.</p>`;

const transport = [
  ["✈️","plane","fly"],["🚆","train","take / catch"],["🚌","bus","take / catch"],["🚇","subway","take"],["🚕","taxi","take"],["🚗","car","drive"],
  ["🏍️","motorcycle","ride"],["🚲","bicycle","ride"],["⛴️","ferry","take"],["🚢","ship","sail"],["🚶","on foot","walk"],["🚐","van","drive / take"]
];
const clothes = [
  ["👕","T-shirt"],["👔","shirt"],["👖","jeans"],["👗","dress"],["🩳","shorts"],["🧥","jacket"],
  ["🧣","scarf"],["🧢","cap"],["👟","sneakers"],["🥾","boots"],["🩱","swimsuit"],["🕶️","sunglasses"]
];
const vocabGrid = (items) => `<div class="vocab-grid">${items.map(([icon, word, verb]) => `<div class="vocab-card"><span class="icon">${icon}</span><strong>${word}</strong>${verb ? `<small>${verb}</small>` : ""}</div>`).join("")}</div>`;

const stages = [
  {
    phase:"Boarding Call", short:"Boarding call", time:10, theme:"theme-orange", interaction:"Whole class → pairs",
    title:"One suitcase. <em>Three stories.</em>", lead:"Today every new word has a destination: a story about where you went, how you traveled, and what you wore.",
    instruction:"Choose one corner: AIR, LAND, SEA, or HOME. Tell a partner about your last trip—or invent one.",
    body:`<div class="grid three"><section class="card"><span class="mini-label">MOVE · 3 MIN</span><p class="big-prompt">plane · train · ferry · bicycle</p><p class="micro">Move to the transport you would choose for a dream trip.</p></section><section class="card accent"><span class="mini-label">PAIR · 4 MIN</span><h3>Fast connections</h3><div class="prompt-line">Where did you go?</div><div class="prompt-line">How did you travel?</div><div class="prompt-line">What did you wear?</div></section><section class="card"><span class="mini-label">MISSION · 3 MIN</span><h3>Complete the route</h3><p>PLAN → PACK → TRAVEL → _____</p>${reveal("destination","PLAN → PACK → TRAVEL → <strong>TELL THE STORY</strong>")}</section></div>`,
    teacher:{objective:"Activate prior knowledge and establish the final communicative goal.",flow:["Label four areas of the room: air, land, sea, home.","Accept real or invented trips; focus on participation.","Collect useful travel verbs without explaining the past yet."],evidence:"Every student produces one destination, one transport word, and one clothing word."}
  },
  {
    phase:"Travel & Transportation", short:"Transport words", time:15, theme:"", interaction:"Teacher ↔ students",
    title:"How can we <em>get there?</em>", lead:"Learn transportation as useful verb-and-noun partnerships, not isolated labels.",
    instruction:"See it, say it, add the verb. Then hide the screen and recall eight combinations.",
    body:`${vocabGrid(transport)}<div class="grid two" style="margin-top:12px"><section class="card coral"><strong>BY + transport</strong><p>by plane · by train · by bus · by car</p></section><section class="card blue"><strong>Exceptions</strong><p>on foot · in a taxi · on the bus · on a bicycle</p></section></div>`,
    teacher:{objective:"Build a bank of transportation nouns with natural verb collocations.",flow:["Drill noun + action: plane/fly, bicycle/ride, car/drive.","Contrast by bus with on the bus.","Run a 60-second pair memory challenge."],evidence:"Pairs recall eight transport words and use six with an accurate action verb."}
  },
  {
    phase:"Choosing Transportation", short:"Choose a route", time:15, theme:"theme-night", interaction:"Pairs → teams",
    title:"Fast, cheap, comfortable—<em>choose.</em>", lead:"The best transportation depends on distance, time, money, and the traveler.",
    instruction:"Choose the best option and defend it with because. More than one answer may be reasonable.",
    body:`<div class="grid four"><section class="mission-card"><span class="icon">🏫</span><h3>2 km to class</h3><p>Sunny day · low budget</p><div class="button-row">${choice("bicycle",1,"t1")}${choice("plane",0,"t1")}</div></section><section class="mission-card"><span class="icon">🏝️</span><h3>An island trip</h3><p>No airport · one suitcase</p><div class="button-row">${choice("ferry",1,"t2")}${choice("subway",0,"t2")}</div></section><section class="mission-card"><span class="icon">🌃</span><h3>Late at night</h3><p>Heavy luggage · 5 km</p><div class="button-row">${choice("taxi",1,"t3")}${choice("on foot",0,"t3")}</div></section><section class="mission-card"><span class="icon">🌍</span><h3>Across the ocean</h3><p>Only eight hours</p><div class="button-row">${choice("plane",1,"t4")}${choice("bicycle",0,"t4")}</div></section></div><div class="card" style="margin-top:12px"><p class="big-prompt">“I would travel by ___ because it is ___.”</p></div>`,
    teacher:{objective:"Select transportation based on constraints and justify decisions.",flow:["Model one answer with because.","After digital checks, challenge a correct answer with a new condition.","Require each team to propose one alternative route."],evidence:"Students make four logical choices and justify at least two in complete sentences."}
  },
  {
    phase:"At the Travel Hub", short:"Travel language", time:15, theme:"theme-blue", interaction:"Pairs",
    title:"Read the signs. <em>Catch the trip.</em>", lead:"Stations and airports have a language of their own. Use it to move from entrance to departure.",
    instruction:"Read the departure board. Ask and answer: Where? When? Which gate or platform? What status?",
    body:`<div class="departure-board"><div class="board-cell"><small>DESTINATION</small><strong>SANTIAGO</strong><span>Flight AX214</span></div><div class="board-cell"><small>DEPARTURE</small><strong>10:45</strong><span>On time</span></div><div class="board-cell"><small>GATE</small><strong>B12</strong><span>Boarding 10:15</span></div><div class="board-cell"><small>BAGGAGE</small><strong>1 BAG</strong><span>20 kg maximum</span></div></div><div class="grid four" style="margin-top:12px"><section class="card"><span class="mini-label">DOCUMENT</span><h3>passport</h3><p>shows your identity</p></section><section class="card"><span class="mini-label">ACCESS</span><h3>boarding pass</h3><p>shows your seat and gate</p></section><section class="card"><span class="mini-label">BAGS</span><h3>luggage</h3><p>what you pack</p></section><section class="card"><span class="mini-label">ACTION</span><h3>board</h3><p>get on the plane</p></section></div>`,
    teacher:{objective:"Interpret essential airport and station information.",flow:["Give students 20 seconds to scan the board.","Hide one detail with your hand and ask for it.","Pairs create two new questions about the board."],evidence:"Students retrieve destination, time, gate, status, and baggage information accurately."}
  },
  {
    phase:"Travel Problem-Solving", short:"Travel desk", time:20, theme:"", interaction:"Pair role-play",
    title:"Plans change. <em>Keep moving.</em>", lead:"A traveler needs clear questions; a travel agent needs practical solutions.",
    instruction:"Generate a problem. Student A explains it; Student B offers a route and confirms the details.",
    body:`<div class="grid two"><section class="card coral"><span class="mini-label">RANDOM TRAVEL PROBLEM</span><div class="generator-output" id="mission-output">Press the button when your partner is ready.</div><button class="generator-button" type="button" data-generator="mission">Generate problem</button></section><section class="card"><span class="mini-label">LANGUAGE BANK</span><div class="prompt-line">How can I get to ___?</div><div class="prompt-line">You can take / catch / ride ___.</div><div class="prompt-line">What time does it leave?</div><div class="prompt-line">It leaves at ___ from gate/platform ___.</div><div class="prompt-line">Let me confirm: ___.</div></section></div><div class="card accent" style="margin-top:12px"><strong>Success:</strong> 8 lines · 2 transport words · 1 time · 1 reason · 1 confirmation</div>`,
    teacher:{objective:"Sustain a functional travel-information exchange.",flow:["Model problem → question → option → reason → confirmation.","Round 1: supported with the language bank; Round 2: hide it.","Listen for communication first; delay correction until the swap."],evidence:"Pairs complete an eight-line exchange and confirm a workable travel plan."}
  },
  {
    phase:"What Are You Wearing?", short:"Clothes words", time:15, theme:"theme-yellow", interaction:"Whole class → pairs",
    title:"Open the suitcase. <em>Name the look.</em>", lead:"Clothing words become memorable when students connect them to real people and real situations.",
    instruction:"Name each item. Then point to something you or a classmate is wearing—respectfully.",
    body:`${vocabGrid(clothes)}<div class="card" style="margin-top:12px"><p class="big-prompt">I can see someone wearing _____.</p><p class="micro">Describe the item, never the person’s body. Participation may use an invented outfit.</p></div>`,
    teacher:{objective:"Develop a practical clothing vocabulary set.",flow:["Elicit before displaying pronunciation.","Add colors and patterns: plain, striped, checked.","Use fictional outfits if students prefer not to describe themselves."],evidence:"Students name ten items and describe three visible or invented clothing details."}
  },
  {
    phase:"Present Progressive", short:"Wearing now", time:15, theme:"theme-aqua", interaction:"Teacher → pairs",
    title:"What <em>are you wearing?</em>", lead:"Use the present progressive to describe clothes on the body right now.",
    instruction:"Build the sentence in three parts: subject + be + wearing + clothes.",
    body:`<div class="grid two"><section class="card"><span class="mini-label">STATEMENT</span><div class="formula">I <b>am wearing</b> a blue shirt.</div><p>He <strong>is wearing</strong> black jeans.<br>They <strong>are wearing</strong> sneakers.</p></section><section class="card"><span class="mini-label">QUESTION + ANSWER</span><div class="formula">What <b>are</b> you <b>wearing</b>?</div><p>I’m wearing a dress and boots.<br>She isn’t wearing a jacket.</p></section></div><div class="grid three" style="margin-top:12px"><section class="card"><p>She ___ wearing a scarf.</p><div class="button-row">${choice("is",1,"w1")}${choice("are",0,"w1")}</div></section><section class="card"><p>What ___ they wearing?</p><div class="button-row">${choice("is",0,"w2")}${choice("are",1,"w2")}</div></section><section class="card"><p>He is ___ boots.</p><div class="button-row">${choice("wear",0,"w3")}${choice("wearing",1,"w3")}</div></section></div>`,
    teacher:{objective:"Form present-progressive statements and questions with wearing.",flow:["Color-code subject, be, and -ing form on the board.","Contrast I wear a uniform every day / I am wearing a uniform now.","Pairs ask, answer, and report about a fictional traveler."],evidence:"Students create one question, one answer, and one third-person report accurately."}
  },
  {
    phase:"Packing for the Trip", short:"Pack smart", time:15, theme:"", interaction:"Small groups",
    title:"Right clothes. <em>Right destination.</em>", lead:"Packing is a decision: weather, activity, culture, luggage space.",
    instruction:"Generate a destination. Pack exactly five items and defend every choice.",
    body:`<div class="grid two"><section class="card blue"><span class="mini-label">DESTINATION GENERATOR</span><div class="generator-output" id="outfit-output">Your suitcase is empty.</div><button class="generator-button" type="button" data-generator="outfit">Choose destination</button></section><section class="card"><span class="mini-label">PACKING LANGUAGE</span><div class="prompt-line">I’m packing ___ because ___.</div><div class="prompt-line">We need / don’t need ___.</div><div class="prompt-line">At the destination, I’m wearing ___.</div><div class="prompt-line">___ is more practical than ___.</div></section></div><div class="grid five" style="margin-top:12px"><div class="card"><strong>1</strong><p>top</p></div><div class="card"><strong>2</strong><p>bottom</p></div><div class="card"><strong>3</strong><p>shoes</p></div><div class="card"><strong>4</strong><p>weather item</p></div><div class="card accent"><strong>5</strong><p>surprise item</p></div></div>`,
    teacher:{objective:"Select and justify clothing for a travel context.",flow:["Groups generate one destination.","Allow exactly five items to create meaningful negotiation.","One member presents the final outfit; others answer challenges."],evidence:"Groups use five clothing words, two wearing sentences, and three reasons."}
  },
  {
    phase:"Past Tense Discovery", short:"was / were", time:20, theme:"theme-night", interaction:"Think → pair → share",
    title:"Yesterday <em>was different.</em>", lead:"Before telling what happened, establish who and where with the past of be.",
    instruction:"Choose was or were. Then transform each statement into a question.",
    body:`<table class="grammar-table"><thead><tr><th>Subject</th><th>Affirmative</th><th>Negative</th><th>Question</th></tr></thead><tbody><tr><td>I / he / she / it</td><td>was</td><td>wasn’t</td><td>Was I/he/she/it…?</td></tr><tr><td>you / we / they</td><td>were</td><td>weren’t</td><td>Were you/we/they…?</td></tr></tbody></table><div class="grid three" style="margin-top:12px"><section class="card"><p>The flight ___ late.</p><div class="button-row">${choice("was",1,"b1")}${choice("were",0,"b1")}</div></section><section class="card"><p>We ___ at gate 12.</p><div class="button-row">${choice("was",0,"b2")}${choice("were",1,"b2")}</div></section><section class="card"><p>___ your bags heavy?</p><div class="button-row">${choice("Was",0,"b3")}${choice("Were",1,"b3")}</div></section></div><div class="card" style="margin-top:12px">${reveal("travel snapshot","Last Saturday, we <strong>were</strong> at the station. It <strong>was</strong> crowded, but the trains <strong>weren’t</strong> late.")}</div>`,
    teacher:{objective:"Use was/were in affirmative, negative, and interrogative forms.",flow:["Anchor was/were on a past-time line.","Drill subject agreement before adding vocabulary.","Pairs convert three statements into questions and short answers."],evidence:"Students select was/were accurately in five of six oral prompts."}
  },
  {
    phase:"Regular Past Verbs", short:"Regular past", time:20, theme:"theme-orange", interaction:"Teams",
    title:"Add -ed. <em>Listen deeper.</em>", lead:"Regular past verbs share a spelling pattern, but the ending has three possible sounds.",
    instruction:"First build the past form. Then sort the final sound: /t/, /d/, or /ɪd/.",
    body:`<div class="grid three"><section class="card"><span class="mini-label">/t/</span><h3>walked · packed · missed</h3><p>No extra syllable.</p></section><section class="card"><span class="mini-label">/d/</span><h3>traveled · arrived · stayed</h3><p>No extra syllable.</p></section><section class="card"><span class="mini-label">/ɪd/</span><h3>visited · needed · decided</h3><p>Add one syllable after /t/ or /d/.</p></section></div><table class="grammar-table" style="margin-top:12px"><thead><tr><th>Rule</th><th>Base</th><th>Past</th></tr></thead><tbody><tr><td>most verbs</td><td>pack</td><td>packed</td></tr><tr><td>final -e</td><td>arrive</td><td>arrived</td></tr><tr><td>consonant + y</td><td>carry</td><td>carried</td></tr><tr><td>short CVC</td><td>stop</td><td>stopped</td></tr></tbody></table><div class="card" style="margin-top:12px"><strong>Pronunciation relay:</strong> Teacher says a verb. Teams show T, D, or ID and use it in a travel sentence.</div>`,
    teacher:{objective:"Form regular past verbs and distinguish -ed pronunciations.",flow:["Teach spelling before pronunciation.","Let students feel the final sound by touching their throat.","Run rapid team rounds; require a sentence after each answer."],evidence:"Teams form six past verbs and identify four of five ending sounds."}
  },
  {
    phase:"Irregular Past Verbs", short:"Irregular past", time:20, theme:"theme-aqua", interaction:"Pairs → whole class",
    title:"No -ed. <em>New shape.</em>", lead:"Irregular verbs change form. Learn them in meaningful travel phrases.",
    instruction:"Tap each verb: 1 = regular, 2 = irregular. Then say the past form aloud.",
    body:`<div class="grid four"><section class="card"><h3>go → went</h3><p>We went to the beach.</p></section><section class="card"><h3>take → took</h3><p>She took the train.</p></section><section class="card"><h3>see → saw</h3><p>I saw the mountains.</p></section><section class="card"><h3>buy → bought</h3><p>They bought tickets.</p></section><section class="card"><h3>wear → wore</h3><p>He wore a jacket.</p></section><section class="card"><h3>leave → left</h3><p>The bus left at nine.</p></section><section class="card"><h3>have → had</h3><p>We had a problem.</p></section><section class="card"><h3>come → came</h3><p>My cousin came with us.</p></section></div><section class="card" style="margin-top:12px">${sort([["visited","one"],["went","two"],["packed","one"],["wore","two"],["arrived","one"],["took","two"]],"verbs")}</section>`,
    teacher:{objective:"Retrieve high-frequency irregular verbs in travel contexts.",flow:["Choral drill base → past → sentence.","Students cover the past forms and quiz each other.","After sorting, pairs create a four-event mini-trip."],evidence:"Students retrieve six irregular forms and use four in connected sentences."}
  },
  {
    phase:"Past Questions & Negatives", short:"Did / didn’t", time:20, theme:"theme-blue", interaction:"Pairs",
    title:"Did you go? <em>No, I didn’t.</em>", lead:"Did carries the past. The main verb returns to its base form.",
    instruction:"Build questions and negatives. Circle did/didn’t; underline the base verb.",
    body:`<div class="grid two"><section class="card"><span class="mini-label">QUESTION</span><div class="formula"><b>Did</b> you <b>take</b> the bus?</div><p>Yes, I did. / No, I didn’t.<br>Where did she go?</p></section><section class="card"><span class="mini-label">NEGATIVE</span><div class="formula">We <b>didn’t miss</b> the flight.</div><p>Not: didn’t missed<br>Not: Did you took…?</p></section></div><div class="grid three" style="margin-top:12px"><section class="card"><p>Did she ___ a jacket?</p><div class="button-row">${choice("wore",0,"d1")}${choice("wear",1,"d1")}</div></section><section class="card"><p>We didn’t ___ the train.</p><div class="button-row">${choice("miss",1,"d2")}${choice("missed",0,"d2")}</div></section><section class="card"><p>Where did they ___?</p><div class="button-row">${choice("went",0,"d3")}${choice("go",1,"d3")}</div></section></div><div class="card coral" style="margin-top:12px"><strong>Interview:</strong> Ask four questions about a real or invented trip. Report two answers to the class.</div>`,
    teacher:{objective:"Form past simple questions, short answers, and negatives with did.",flow:["Use a visual rule: DID = past; VERB = base.","Students repair the two common errors before selecting.","Run interviews, then require third-person reporting."],evidence:"Pairs ask four accurate questions and report one positive and one negative answer."}
  },
  {
    phase:"Travel Story Lab", short:"Build the story", time:25, theme:"theme-night", interaction:"Small groups",
    title:"Turn a trip into <em>a story.</em>", lead:"A memorable story has a setting, a sequence, a problem, and a final reaction.",
    instruction:"Generate your story seed. Build six connected sentences; every group member must contribute.",
    body:`<div class="grid two"><section class="card"><span class="mini-label">STORY SEED</span><div class="generator-output" id="story-output">Destination unknown. Press when the group is ready.</div><button class="generator-button" type="button" data-generator="story">Generate story</button></section><section class="card"><span class="mini-label">STORY ENGINE</span><div class="timeline"><div><small>01 · SETTING</small><strong>Last… we were…</strong></div><div><small>02 · ACTION</small><strong>First, we…</strong></div><div><small>03 · PROBLEM</small><strong>Suddenly…</strong></div><div><small>04 · ENDING</small><strong>Finally…</strong></div></div><div class="prompt-line">What transport did you take?</div><div class="prompt-line">What were you wearing?</div><div class="prompt-line">What happened?</div></section></div><div class="grid four" style="margin-top:12px"><div class="card"><strong>2</strong><p>transport words</p></div><div class="card"><strong>2</strong><p>clothing items</p></div><div class="card"><strong>4</strong><p>past verbs</p></div><div class="card accent"><strong>1</strong><p>audience question</p></div></div>`,
    teacher:{objective:"Integrate transportation, clothing, and past grammar in a coherent narrative.",flow:["Groups assign roles: route planner, language checker, storyteller, questioner.","Plan with six keywords, not a full script.","After each story, the audience asks one past-tense question."],evidence:"Groups deliver a connected story with all four content targets and shared participation."}
  },
  {
    phase:"Arrival Check", short:"Review & exit", time:15, theme:"theme-yellow", interaction:"Teams → individual",
    title:"Land the lesson. <em>Prove the learning.</em>", lead:"Retrieve the language quickly, then use it independently in one final travel snapshot.",
    instruction:"Complete the team check without notes. The exit ticket is individual.",
    body:`<div class="grid two"><section class="card"><span class="mini-label">TEAM CHECK · 7 MIN</span><ol><li>Name four types of transportation.</li><li>Ask: What are you wearing?</li><li>Complete: Yesterday we ___ at the station.</li><li>Give the past of go, take, wear, and arrive.</li><li>Correct: Did she wore boots?</li></ol>${reveal("sample answers","plane/train/bus/ferry · I’m wearing… · <strong>were</strong> · went/took/wore/arrived · Did she <strong>wear</strong> boots?")}</section><section class="card accent"><span class="mini-label">EXIT TICKET · 8 MIN</span><h3>My five-line trip</h3><ol><li>Where and when?</li><li>How did you travel?</li><li>What were you wearing?</li><li>What happened?</li><li>How did you feel?</li></ol><p class="micro">Real or invented. Use at least three past verbs.</p></section></div>`,
    teacher:{objective:"Check retrieval and independent transfer across all three lesson themes.",flow:["Teams commit before revealing answers.","Exit ticket is silent and individual.","Sort tickets into Ready / Quick review / Reteach."],evidence:"Students produce five connected sentences with accurate transport, clothing, and three past forms."}
  }
];

const generators = {
  mission:["Your train was canceled. Reach the city before 6:00 p.m.","You have heavy luggage and only $15. The hotel is 8 km away.","You missed the last bus. Find a safe alternative.","The airport changed your gate. Ask for the new location and boarding time.","Your group needs to cross to an island, but one person dislikes flying."],
  outfit:["A rainy weekend in London · 12°C","A beach day in Punta Cana · 31°C","A mountain hike in Jarabacoa · 16°C","A formal dinner in New York · 8°C","A bicycle tour in Santo Domingo · 28°C"],
  story:["You went to the wrong station while wearing formal clothes.","Your ferry left early, but your luggage was still at the hotel.","It started raining during a bicycle tour and nobody had a jacket.","You met a famous person on the train and took a surprising photo.","Your plane was delayed, so the airport became your hotel for one night."]
};

let current = 0;
const completed = new Set(JSON.parse(localStorage.getItem("english2-unit3-complete") || "[]"));
const stage = document.getElementById("lesson-stage");
const nav = document.getElementById("lesson-nav");

function teacherMarkup(item){return `<div class="teacher-meta"><div><small>TIME</small><strong>${item.time} min</strong></div><div><small>INTERACTION</small><strong>${item.interaction}</strong></div></div><section class="note-block"><h3>Learning objective</h3><p>${item.teacher.objective}</p></section><section class="note-block"><h3>Facilitation flow</h3><ul>${item.teacher.flow.map(step=>`<li>${step}</li>`).join("")}</ul></section><section class="note-block"><h3>Success evidence</h3><p>${item.teacher.evidence}</p></section>`}
function bindActions(){
  stage.querySelectorAll("[data-answer]").forEach(button=>button.addEventListener("click",()=>{const group=button.dataset.group;stage.querySelectorAll(`[data-group="${group}"]`).forEach(item=>{item.disabled=true;if(item.dataset.answer==="1")item.classList.add("correct")});if(button.dataset.answer!=="1")button.classList.add("wrong")}));
  stage.querySelectorAll("[data-reveal]").forEach(button=>button.addEventListener("click",()=>{const panel=button.nextElementSibling;panel.classList.toggle("visible");button.textContent=panel.classList.contains("visible")?"Hide answer":button.textContent.replace("Hide answer","Reveal answer")}));
  stage.querySelectorAll("[data-sort]").forEach(bank=>bank.querySelectorAll(".sort-button").forEach(button=>button.addEventListener("click",()=>{button.dataset.choice=button.dataset.choice==="one"?"two":"one";button.classList.remove("wrong")})));
  stage.querySelectorAll("[data-check]").forEach(button=>button.addEventListener("click",()=>{const id=button.dataset.check;const bank=stage.querySelector(`[data-sort="${id}"]`);let correct=0;bank.querySelectorAll(".sort-button").forEach(item=>{const ok=item.dataset.choice===item.dataset.correct;item.classList.toggle("wrong",!ok);if(ok)correct++});stage.querySelector(`[data-feedback="${id}"]`).textContent=`${correct} / ${bank.children.length} correct. 1 = regular; 2 = irregular.`}));
  stage.querySelectorAll("[data-reset]").forEach(button=>button.addEventListener("click",()=>{const id=button.dataset.reset;stage.querySelectorAll(`[data-sort="${id}"] .sort-button`).forEach(item=>{delete item.dataset.choice;item.classList.remove("wrong")});stage.querySelector(`[data-feedback="${id}"]`).textContent="Tap each item: 1 = regular, 2 = irregular."}));
  stage.querySelectorAll("[data-generator]").forEach(button=>button.addEventListener("click",()=>{const type=button.dataset.generator;const output=document.getElementById(`${type}-output`);output.textContent=generators[type][Math.floor(Math.random()*generators[type].length)]}));
}
function render(){
  const item=stages[current];stage.className=`lesson-stage ${item.theme||""}`;stage.innerHTML=`<div class="stage-kicker"><span>${item.phase}</span><span>${item.time} MIN · ${item.interaction}</span></div><h${current===0?"1":"2"}>${item.title}</h${current===0?"1":"2"}><p class="stage-lead">${item.lead}</p><div class="stage-instruction"><span>→</span><span>${item.instruction}</span></div>${item.body}`;
  document.getElementById("teacher-content").innerHTML=teacherMarkup(item);document.getElementById("phase-label").textContent=item.short;document.getElementById("stage-counter").textContent=`${String(current+1).padStart(2,"0")} / ${String(stages.length).padStart(2,"0")}`;
  const elapsed=stages.slice(0,current).reduce((sum,s)=>sum+s.time,0);document.getElementById("elapsed-label").textContent=`${elapsed} / 240 min`;document.getElementById("progress-bar").style.width=`${((current+1)/stages.length)*100}%`;
  document.getElementById("prev-button").disabled=current===0;document.getElementById("next-button").disabled=current===stages.length-1;const complete=completed.has(current);document.getElementById("complete-button").setAttribute("aria-pressed",String(complete));document.getElementById("complete-button").textContent=complete?"✓ Complete":"○ Mark complete";
  nav.querySelectorAll(".route-link").forEach((link,index)=>{link.classList.toggle("active",index===current);link.classList.toggle("done",completed.has(index))});nav.children[current]?.scrollIntoView({block:"nearest"});bindActions();stage.focus({preventScroll:true});history.replaceState(null,"",`index.html?stage=${current+1}`);
}
nav.innerHTML=stages.map((item,index)=>`<button class="route-link" type="button" data-index="${index}"><span class="route-number">${String(index+1).padStart(2,"0")}</span><span class="route-copy"><strong>${item.short}</strong><small>${item.phase}</small></span><span class="route-time">${item.time}m</span></button>`).join("");
nav.addEventListener("click",event=>{const button=event.target.closest("[data-index]");if(button){current=Number(button.dataset.index);render()}});
document.getElementById("prev-button").addEventListener("click",()=>{if(current>0){current--;render()}});document.getElementById("next-button").addEventListener("click",()=>{if(current<stages.length-1){current++;render()}});document.getElementById("home-button").addEventListener("click",()=>{current=0;render()});
document.getElementById("complete-button").addEventListener("click",()=>{completed.has(current)?completed.delete(current):completed.add(current);localStorage.setItem("english2-unit3-complete",JSON.stringify([...completed]));render()});
function setTeacher(open){document.getElementById("teacher-drawer").classList.toggle("open",open);document.getElementById("teacher-drawer").setAttribute("aria-hidden",String(!open));document.getElementById("drawer-backdrop").classList.toggle("visible",open);document.getElementById("teacher-button").setAttribute("aria-pressed",String(open))}
document.getElementById("teacher-button").addEventListener("click",()=>setTeacher(!document.getElementById("teacher-drawer").classList.contains("open")));document.getElementById("teacher-close").addEventListener("click",()=>setTeacher(false));document.getElementById("drawer-backdrop").addEventListener("click",()=>setTeacher(false));
document.getElementById("rail-toggle").addEventListener("click",()=>{document.body.classList.toggle(innerWidth<=760?"mobile-rail":"rail-collapsed")});document.getElementById("fullscreen-button").addEventListener("click",()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>{}));
const timerDialog=document.getElementById("timer-dialog"),timerDisplay=document.getElementById("timer-display");let timerInitial=300,timerSeconds=300,timerHandle=null;const drawTimer=()=>timerDisplay.textContent=`${String(Math.floor(timerSeconds/60)).padStart(2,"0")}:${String(timerSeconds%60).padStart(2,"0")}`;const stopTimer=()=>{clearInterval(timerHandle);timerHandle=null;document.getElementById("timer-start").textContent=timerSeconds===0?"Done":"Start"};
document.getElementById("timer-button").addEventListener("click",()=>timerDialog.showModal());timerDialog.querySelectorAll("[data-minutes]").forEach(button=>button.addEventListener("click",()=>{stopTimer();timerDialog.querySelectorAll("[data-minutes]").forEach(item=>item.classList.remove("active"));button.classList.add("active");timerInitial=Number(button.dataset.minutes)*60;timerSeconds=timerInitial;drawTimer()}));document.getElementById("timer-start").addEventListener("click",event=>{if(timerHandle){stopTimer();return}if(timerSeconds===0)timerSeconds=timerInitial;event.currentTarget.textContent="Pause";timerHandle=setInterval(()=>{timerSeconds--;drawTimer();if(timerSeconds<=0){stopTimer();timerDisplay.textContent="TIME!"}},1000)});document.getElementById("timer-reset").addEventListener("click",()=>{stopTimer();timerSeconds=timerInitial;drawTimer()});
document.addEventListener("keydown",event=>{if(event.target.matches("button,input"))return;if(event.key==="ArrowRight"&&current<stages.length-1){current++;render()}if(event.key==="ArrowLeft"&&current>0){current--;render()}if(event.key.toLowerCase()==="t")setTeacher(!document.getElementById("teacher-drawer").classList.contains("open"));if(event.key==="Escape")setTeacher(false)});
const requested=Number(new URLSearchParams(location.search).get("stage"));if(requested>=1&&requested<=stages.length)current=requested-1;render();drawTimer();
